# Generated by Django 5.2.7 on 2025-10-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userprofile_reserve_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='target_reserve',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_categories_created',
            field=models.BooleanField(default=False),
        ),
    ]
