# Generated by Django 5.2.7 on 2025-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_systemnotification_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('c', 'Сом'), ('r', 'Рубль'), ('$', 'Доллар'), ('€', 'Евро')], default='c', max_length=1),
        ),
    ]
