# Generated by Django 5.2.7 on 2025-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
