# Generated by Django 5.2.7 on 2025-10-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_target_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='is_chat',
            field=models.BooleanField(default=False),
        ),
    ]
