# Generated by Django 5.2.7 on 2025-10-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('paid', 'Погашенный'), ('delay_7', 'Отсрочка 7 дней')], default='active', max_length=10),
        ),
    ]
