# Generated by Django 5.2.7 on 2025-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_debt_options_alter_debt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление о просрочке отправлено'),
        ),
    ]
