# Generated by Django 5.2.7 on 2025-10-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_debt_overdue_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Погашенная сумма'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('partially_paid', 'Частично погашен'), ('paid', 'Погашенный'), ('delay_7', 'Отсрочка 7 дней')], default='active', max_length=15),
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание к платежу')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.debt')),
            ],
            options={
                'verbose_name': 'Платеж по долгу',
                'verbose_name_plural': 'Платежи по долгам',
                'ordering': ['-payment_date'],
            },
        ),
    ]
