# Generated by Django 5.2.7 on 2025-10-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_debt_paid_amount_alter_debt_status_debtpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/covers/', verbose_name='Обложка уведомления'),
        ),
    ]
