# Generated by Django 5.2.7 on 2025-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
