# Generated by Django 5.2.7 on 2025-11-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('c', 'Сом'), ('r', 'Рубль'), ('$', 'Доллар'), ('€', 'Евро'), ('₸', 'Тенге')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], default='en', max_length=2),
        ),
    ]
