# Generated by Django 5.2.7 on 2025-11-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_userprofile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча'), ('uk', 'Українська')], default='en', max_length=2),
        ),
    ]
